### ISSUE TITLE
NavBar

### ISSUE THREAD

**Issue by monginadiana** [NaiDevOpsCom/NaiDevOpsCom#1]
1. Create the NavBar Section, :

- [ ] Add the Logo Item
- [ ] The NavBar Items
- [ ] The partner with us as a Link.
-
![Screenshot from 2024-01-15 16-37-15](https://github.com/NaiDevOpsCom/NaiDevOpsCom/assets/87479141/4e3acb4a-a762-484d-846f-98d4d2b00b91)

**Comment by McRonaah** [comment]
I will be working on this
